"""init schema

Revision ID: bdba22b95b7e
Revises: 
Create Date: 2026-02-23 21:47:27.280083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdba22b95b7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=8), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('organization', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('raw_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org', sa.String(length=50), nullable=False),
    sa.Column('data_character', sa.String(length=200), nullable=False),
    sa.Column('capture_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hardware_desc', sa.String(length=300), nullable=False),
    sa.Column('software_desc', sa.String(length=300), nullable=False),
    sa.Column('processing_degree', sa.String(length=300), nullable=False),
    sa.Column('capture_points', sa.Integer(), nullable=False),
    sa.Column('schema_file_id', sa.Integer(), nullable=True),
    sa.Column('description_file_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['description_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['schema_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_groups_capture_end'), 'raw_groups', ['capture_end'], unique=False)
    op.create_index(op.f('ix_raw_groups_capture_points'), 'raw_groups', ['capture_points'], unique=False)
    op.create_index(op.f('ix_raw_groups_capture_start'), 'raw_groups', ['capture_start'], unique=False)
    op.create_index(op.f('ix_raw_groups_data_character'), 'raw_groups', ['data_character'], unique=False)
    op.create_index(op.f('ix_raw_groups_org'), 'raw_groups', ['org'], unique=False)
    op.create_table('raw_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('point', sa.String(length=10), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('t_min', sa.DateTime(timezone=True), nullable=True),
    sa.Column('t_max', sa.DateTime(timezone=True), nullable=True),
    sa.Column('packets_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['raw_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_traces_group_id'), 'raw_traces', ['group_id'], unique=False)
    op.create_index(op.f('ix_raw_traces_t_max'), 'raw_traces', ['t_max'], unique=False)
    op.create_index(op.f('ix_raw_traces_t_min'), 'raw_traces', ['t_min'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_traces_t_min'), table_name='raw_traces')
    op.drop_index(op.f('ix_raw_traces_t_max'), table_name='raw_traces')
    op.drop_index(op.f('ix_raw_traces_group_id'), table_name='raw_traces')
    op.drop_table('raw_traces')
    op.drop_index(op.f('ix_raw_groups_org'), table_name='raw_groups')
    op.drop_index(op.f('ix_raw_groups_data_character'), table_name='raw_groups')
    op.drop_index(op.f('ix_raw_groups_capture_start'), table_name='raw_groups')
    op.drop_index(op.f('ix_raw_groups_capture_points'), table_name='raw_groups')
    op.drop_index(op.f('ix_raw_groups_capture_end'), table_name='raw_groups')
    op.drop_table('raw_groups')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_table('files')
    # ### end Alembic commands ###
